name: 'Webhook Action'
author: "Joel Male"
description: 'Send a webhook event to anywhere!'
branding:
  icon: 'alert-octagon'  
  color: 'gray-dark'
inputs:
  url:
    description: 'The url to send the webhook event to'
    required: true
  headers:
    description: 'Additional headers to send alongside the defaults'
    required: false
  body:
    description: 'The data sent to the webhook'
    required: false
  insecure:
    description: 'Enables calling to known self-signed or invalid SSL certificates'
    required: false
  github_event_payload:
    description: 'Include the github event payload that triggered the action in the payload'
    required: false
outputs:
  status: 
    description: 'The status of the webhook event'
runs:
  using: 'node20'
  main: 'dist/index.js'
